<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Comment;
use App\Models\User;
use App\Models\Notification;
use App\Http\Controllers\NotificationController;

class CommentsController extends Controller
{
    //
    public function index(Request $request)
    {
    }

    public function add(Request $request)
    {
        $user_id = auth()->user()->id;

        $commentText = $request->post('text');
        $video_id = $request->post('video_id');
        $video_title = $request->post('video_title');
        $second = $request->post('second');

        $comment = new Comment();
        $comment->text = $commentText;
        $comment->video_id = $video_id;
        $comment->youtube_second = $second;

        $user_comment = User::find($user_id);
        $user_comment->comment()->save($comment);

        // Send notification about this message.

        // Generate notification at this action.
        $notificationController = new NotificationController;
        $contractController = new ContractController;
        $notification = new Notification;
        $userController = new UserController;
        $user_id = $request->user()->id;
        $user_type = $request->session()->get('profile_type');
        $profile = $request->session()->get('profile');
        $user = $userController->get_user_from_id($user_id);

        //In case notification is generated by a content creator.

        if ($user_type == 1) {
            $manager = $contractController->get_contract_manager($profile->id);
            $manager_user = $userController->get_user_from_manager($manager);
            if ($manager_user != null) {
                $notification->from_user = $user->id;
                $notification->to_user = $manager_user->id;
                $notification->notification_type = 1;
                $notification->message = 'New Comment added for video "' . $video_title . '": ' . $commentText;
                $notification->target_id = $video_id . ":" . $comment->id;
                $notification->save();
            }
            //In case notification is generated by a content manager.   
        } else if ($user_type == 2) {
            $creator_user = $request->session()->get('creator_user_profile');
            if (isset($creator_user)) {
                $notification->from_user = $user->id;
                $notification->to_user = $creator_user->id;
                $notification->notification_type = 1;
                $notification->message = 'New Comment added for video "' . $video_title . '": ' . $commentText;
                $notification->target_id = $video_id . ":" . $comment->id;
                $notification->save();
            }
        }
        return $comment->id;
    }

    public function list_by_id($video_id)
    {

        $comments = Comment::with('user')->where('video_id', $video_id)->get();
        return $comments;
    }

    public function admin_list(Request $request){
        $comments = Comment::with('user')->get();
        return view('admin/comments')->with('comments',$comments);
    }
}
